project:
  type: website
  output-dir: docs

website:
  title: "US tariffs and their effects on Magnificent Seven stocks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Terminalogies.qmd
        text: Terminologies
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




